server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/medhub
  sql:
    init:
      platform: postgres
      mode: never
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    visibility:
      field: none
      setter: none
      getter: any
      is-getter: any
    deserialization:
      fail-on-unknown-properties: false
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
medhub:
  security:
    encryption:
      key: ${ENCRYPTION_KEY}
    hashing:
      salt: ${HASHING_SALT}
database:
  admin:
    name: "Szymon"
    surname: "Lis"
    email: "szymon.lis@gmail.com"
    phoneNumber: "123456789"
    password: ${ADMIN_PASSWORD}
